config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :projects
  resources :stylings
  resources :sketches

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "300x300#" }, default_url:  "/system/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
	validates_attachment_presence :photo
end

app/models/sketche.rb
class Sketche < ActiveRecord::Base
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "300x300#" }, default_url:  "/system/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
	validates_attachment_presence :photo
end

app/models/styling.rb
class Styling < ActiveRecord::Base
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "300x300#" }, default_url:  "/system/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
	validates_attachment_presence :photo
end

app/models/video.rb
class Video < ActiveRecord::Base
	has_attached_file :photo, styles: { medium: "800x450>", thumb: "800x450#" }, default_url:  "/system/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
	validates_attachment_presence :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  
  def index
    @projects = Project.order('created_at DESC').all
  end
end

app/controllers/sketches_controller.rb
class SketchesController < InheritedResources::Base

  def index
    @sketches = Sketche.order('created_at DESC').all
  end

end

app/controllers/stylings_controller.rb
class StylingsController < ApplicationController

  def index
    @stylings = Styling.order('created_at DESC').all
  end

end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base

  def index
    @videos = Video.order('created_at DESC').all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

 def is_active?(link_path)
  current_page?(link_path) ? "btn btn-default btn-sm btn-nav active" : "btn btn-default btn-sm btn-nav"
 end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/helpers/stylings_helper.rb
module StylingsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <div class="row" style="height:50px;"></div>
  <div class="container">
  	<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12">
	  <div id="main-jumbotron" class="jumbotron vertical-center">
		  <div id="content">
		    <%= yield %>
		  </div>
		  <div id="title" class="text-center">
		  	<%= link_to 'WIOLA ULIASZ', static_path(id: 'index') %>
		  </div>
		  <div id="menu" class="text-center">	   
		    <%= link_to 'styling', stylings_path, class: is_active?(stylings_path) %>
		    <%= link_to 'sketches', sketches_path, class: is_active?(sketches_path) %>
		    <%= link_to 'projects', projects_path, class: is_active?(projects_path) %>
		    <%= link_to 'video', videos_path, class: is_active?(videos_path) %>
		    <%= link_to 'contact', static_path(id: 'contact'), class: is_active?(static_path(id: 'contact')) %>
	      </div>
   	  </div>
   	  <div id="www" class="text-center lead" >
   	  	<%= link_to 'www.wiolauliasz.com', 'http://www.wiolauliasz.com' %>
	  </div>
	</div>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>

app/views/pages/contact.html.erb
<% content_for :title, "Contact | Wiola Uliasz" %>
<div id="logo"><%= image_tag "logo.png", height: "50px" %></div>
<div id="contact_email" class="text-center">
<%= mail_to 'contact@wiolauliasz.com', 'contact@wiolauliasz.com' %>
</div>
<div id="contact_phone" class="text-center" title="Check my availability for your project!">
+48 668 042 575
</div>
<div id="contact_social" class="row text-center col-sm-8 col-sm-offset-2">
	<div class="col-sm-4 contact_fa">
		<a href="http://www.facebook.com/wiolauliasz" target="blank"  class="fa fa-facebook-official fa-3x" title="Visit my Facebook page." aria-hidden="true"></a>
	</div>
	<div class="col-sm-4 contact_fa">
		<a href="http://wuzwwa.tumblr.com" target="blank"  class="fa fa-tumblr-square fa-3x" aria-hidden="true" title="Visit my Tumblr page."></a>
	</div>
	<div class="col-sm-4 contact_fa">
		<a href="http://instagram.com/wiolauliasz" target="blank"  class="fa fa-instagram fa-3x" aria-hidden="true" title="Visit my Instagram page."></a>
	</div>
</div>

app/views/pages/index.html.erb
<% content_for :title, "Wiola Uliasz | Wiola Uliasz" %>
<div class="text-center">
	<div id="logo"><%= image_tag "logo.png", height: "50px" %></div>
	<%= image_tag "girl.png" %>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Projects | Wiola Uliasz" %>
<% @projects.each_slice(4).each do |group| %>
  <div class="row">
    <div class="col-md-12">
      <% group.each do |image| %>
        <div class="col-md-3 col-sm-3 col-xs-6 text-center">
          <%= link_to image.photo.url, class: "fancybox", rel: "gallery", title:image.description do %>
            <%= image_tag image.photo.url(:thumb), class: "img-responsive img-thumbnail img-custom" %>
          <% end %>
        </div>
      <% end %>
    </div>
 </div>
<% end %>

app/views/sketches/index.html.erb
<% content_for :title, "Sketches | Wiola Uliasz" %>
<% @sketches.each_slice(4).each do |group| %>
  <div class="row">
    <div class="col-md-12">
      <% group.each do |image| %>
        <div class="col-md-3 col-sm-3 col-xs-6 text-center">
          <%= link_to image.photo.url, class: "fancybox", rel: "gallery", title:image.description do %>
            <%= image_tag image.photo.url(:thumb), class: "img-responsive img-thumbnail img-custom" %>
          <% end %>
        </div>
      <% end %>
    </div>
 </div>
<% end %>
 

app/views/stylings/index.html.erb
<% content_for :title, "Styling | Wiola Uliasz" %>
<% @stylings.each_slice(4).each do |group| %>
  <div class="row">
    <div class="col-md-12">
      <% group.each do |image| %>
        <div class="col-md-3 col-sm-3 col-xs-6 text-center">
          <%= link_to image.photo.url, class: "fancybox", rel: "gallery", title:image.description do %>
            <%= image_tag image.photo.url(:thumb), class: "img-responsive img-thumbnail img-custom" %>
          <% end %>
        </div>
      <% end %>
    </div>
 </div>
<% end %>
 

app/views/videos/index.html.erb
<% content_for :title, "Video | Wiola Uliasz" %>
<% @videos.each_slice(2).each do |group| %>
  <div class="row">
    <div class="col-md-12">
      <% group.each do |video| %>
        <div class="col-md-6 col-sm-6 col-xs-12 text-center">
          <%= link_to video.video_url, class: "various fancybox.iframe", rel: "gallery", title:video.description do %>
            <%= image_tag video.photo.url(:thumb), class: "img-responsive img-thumbnail img-custom" %>
          <% end %>
        </div>
      <% end %>
    </div>
 </div>
<% end %>
 